[package]
name = "aoc-2021"
version = "0.1.0"
edition = "2021"

[features]
day_1 = []
day_2 = []
day_3 = []
day_4 = []
day_5 = []
day_6 = []
day_7 = []
# Insert new day feature here

part_1 = []
part_2 = []

logging = []

[dependencies]
